# This is a development docker-compose file. It's not really intended to be used in production.
# But if you want to manually build urusai, you can use this file.

version: '3.0'

services:
  urusai:
    image: korewachino/urusai:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tts:/urusai/tts

    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=sqlite:database.db